server:
  port: 8080
#说明日志文件在哪里
logging:
  path: D:\ideaworkspace\obs\logs
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/china?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class: com.mysql.jdbc.Driver
    testWhileIdle : true
    validationQuery: SELECT 1
    sql-script-encoding: utf-8
    timeBetweenEvictionRunsMillis: 3600000
    ReadTimeout: 60000
    ConnectTimeout: 60000
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
      master:
      nodes:

