server:
  port: 8080
#说明日志文件在哪里
logging:
  path: D:\ideaworkspace\obs\logs
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource1:
    url: jdbc:mysql://166.111.42.46:3306/china?allowMultiQueries=true&autoReconnect=true
    username: curr
    password: Je5i2E5En1mE
    driver-class: com.mysql.jdbc.Driver
    testWhileIdle : true
    validationQuery: SELECT 1
    sql-script-encoding: utf-8
    timeBetweenEvictionRunsMillis: 3600000
    ReadTimeout: 60000
    ConnectTimeout: 60000
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
      master:
      nodes:

